=== verah-lab/c2vba/Source/Apps/datex2mst/mstBuilder/config/mstDefinition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:def="http://www.heuboe.de/mst/definition" targetNamespace="http://www.heuboe.de/mst/definition"
	xmlns:cfg="http://www.heuboe.de/mst.config" 
	elementFormDefault="qualified">

	<xs:import
		namespace="http://www.heuboe.de/mst/config" 
		schemaLocation="mstConfig.xsd"
	/>
	
	<xs:element name="mstDefinition" type="def:MstDefinition"/>

      <xs:complexType name="MstEntry">
        <xs:sequence>
          <xs:element name="datakindName" type="xs:string"/>
          <xs:element name="column" type="xs:string"/>
          <xs:element name="columnCharacteristic" type="xs:string" minOccurs="0"/>
          <xs:element name="validInterval" type="xs:int"/>

<!--  
      Columns may hold aggregated values of different periods.
      Period selection is done here 
-->
          <xs:element name="period" type="xs:int" minOccurs="0"/>
          <xs:element name="filterColumn" type="xs:string" minOccurs="0"/>
          <xs:element name="filterValue" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:complexType>
      
      <xs:complexType name="MstEntries">
        <xs:sequence>
          <xs:element maxOccurs="unbounded" minOccurs="0" name="item" type="def:MstEntry"/>
        </xs:sequence>
      </xs:complexType>
      
      <xs:complexType name="subObjNames">
        <xs:sequence>
          <xs:element maxOccurs="unbounded" name="item" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      
      <xs:complexType name="MstObjFilter">
        <xs:sequence>
          <xs:element name="referenceType" type="xs:string" minOccurs="0"/>
          <xs:element name="type" type="xs:string" minOccurs="0"/>
          <xs:element name="id" type="xs:string" minOccurs="0"/>
          <xs:element name="name" type="xs:string" minOccurs="0"/>
          <xs:element name="subObjIds" type="def:subObjNames" minOccurs="0"/>
        </xs:sequence>   
 	<xs:attribute name="excluded" type="xs:boolean" default="false" />

      </xs:complexType>

<!--	  
      <xs:complexType name="MstObjFilter">
        <xs:sequence>
          <xs:element name="id" type="xs:string"/>
          <xs:element name="subObjIds" type="def:subObjNames" minOccurs="0"/>
        </xs:sequence>
      </xs:complexType>
-->      
      <xs:complexType name="MstObjFilters">
        <xs:sequence>
          <xs:element maxOccurs="unbounded" minOccurs="0" name="item" type="def:MstObjFilter"/>
        </xs:sequence>
      </xs:complexType>
      
      <xs:complexType name="MstRoadFilter">
        <xs:sequence>
          <xs:element name="name" type="xs:string"/>
          <xs:element name="startOffset" type="xs:int"/>
          <xs:element name="endOffset" type="xs:int"/>
        </xs:sequence>
      </xs:complexType>
      
      <xs:complexType name="MstRoadFilters">
        <xs:sequence>
          <xs:element maxOccurs="unbounded" minOccurs="0" name="item" type="def:MstRoadFilter"/>
        </xs:sequence>
      </xs:complexType>
      
      <xs:complexType name="MstFilter">
        <xs:sequence>
          <xs:element name="subObjType" type="xs:string" minOccurs="0"/>
          <xs:element name="objFilters" type="def:MstObjFilters" minOccurs="0"/>
          <xs:element name="roadFilters" type="def:MstRoadFilters" minOccurs="0"/>
        </xs:sequence>
      </xs:complexType>
      
      <xs:complexType name="MstDefinition">
        <xs:sequence>
          <xs:element name="name" type="xs:string"/>
          <xs:element name="description" type="xs:string"/>
          <xs:element name="defVersion" type="xs:string"/>
          <xs:element name="lclVersion" type="xs:string" minOccurs="0"/>
		  
		  <!-- Valid values: qkurz, qname  -->
          <xs:element name="qNameMode" type="xs:string" minOccurs="0"/>
		  
          <xs:element name="columnEntries" type="def:MstEntries"/>
          <xs:element name="filter" type="def:MstFilter" minOccurs="0"/>
          <xs:element name="active" type="xs:boolean"/>
        </xs:sequence>
      </xs:complexType>
      
      <xs:complexType name="MstDefinitionList">
        <xs:sequence>
          <xs:element maxOccurs="unbounded" minOccurs="0" name="item" type="def:MstDefinition"/>
        </xs:sequence>
      </xs:complexType>
      
	
</xs:schema>

=== verah-lab/c2vba/Source/Apps/datex2mst/mstBuilder/config/importMDM_D2DataMapping/data/mstDefinitionTT_VZH_MDM.xml
<?xml version="1.0" encoding="utf-8"?>
<def:mstDefinition
    xmlns:def="http://www.heuboe.de/mst/definition"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.heuboe.de/mst/definition mstDefinition.xsd ">
  <def:name>TT_VZH_MDM</def:name>
  <def:description>VZH Reise-und Verlustzeiten auf RDS-Segmenten</def:description>
  <def:defVersion>1</def:defVersion>
  <def:qNameMode>qkurz</def:qNameMode>
  <def:columnEntries>
    <def:item>
      <def:datakindName>vzh_losstime_ext</def:datakindName>
      <def:column>free_travel_time</def:column>
      <def:columnCharacteristic/>
      <def:validInterval>300</def:validInterval>
      <def:period>60</def:period>
    </def:item>
  </def:columnEntries>
  
 <!-- 
  <def:filter>
    <def:subObjType>hugo</def:subObjType>
    <def:objFilters>
      <def:item>
        <def:id>5</def:id>
        <def:subObjIds>
          <def:item>eins</def:item>
          <def:item>zwei</def:item>
        </def:subObjIds>
      </def:item>
    </def:objFilters>
    <def:roadFilters>
      <def:item>
        <def:name>otto1</def:name>
        <def:startOffset>1</def:startOffset>
        <def:endOffset>2</def:endOffset>
      </def:item>
      <def:item>
        <def:name>otto2</def:name>
        <def:startOffset>3</def:startOffset>
        <def:endOffset>4</def:endOffset>
      </def:item>
    </def:roadFilters>
  </def:filter>
-->
  <def:active>false</def:active>
</def:mstDefinition>

=== verah-lab/c2vba/Source/Apps/datex2mst/mstBuilder/config/mstDefinition_UFD_SimTD.xml
<?xml version="1.0" encoding="utf-8"?>
<def:mstDefinition
    xmlns:def="http://www.heuboe.de/mst/definition"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.heuboe.de/mst/definition mstDefinition.xsd ">
  <def:name>UFD</def:name>
  <def:description>Umfelddaten</def:description>
  <def:defVersion>1</def:defVersion>
  <def:columnEntries>

    <def:item>
      <def:datakindName>DaUFDSichtWeite</def:datakindName>
      <def:column>Messwert</def:column>
      <def:validInterval>900</def:validInterval>
    </def:item>

    <def:item>
      <def:datakindName>DaUFDWFD</def:datakindName>
      <def:column>Messwert</def:column>
      <def:validInterval>900</def:validInterval>
    </def:item>

    <def:item>
      <def:datakindName>DaUFDNiederInten</def:datakindName>
      <def:column>Messwert</def:column>
      <def:validInterval>900</def:validInterval>
    </def:item>

    <def:item>
      <def:datakindName>DaUFDLuftTemp</def:datakindName>
      <def:column>Messwert</def:column>
      <def:validInterval>900</def:validInterval>
    </def:item>

    <def:item>
      <def:datakindName>DaUFDWindGeschw</def:datakindName>
      <def:column>Messwert</def:column>
      <def:validInterval>900</def:validInterval>
    </def:item>

    <def:item>
      <def:datakindName>DaUFDWindGeschwMax</def:datakindName>
      <def:column>Messwert</def:column>
      <def:validInterval>900</def:validInterval>
    </def:item>

    <def:item>
      <def:datakindName>DaUFDNiederArt</def:datakindName>
      <def:column>Messwert</def:column>
      <def:validInterval>900</def:validInterval>
    </def:item>

    <def:item>
      <def:datakindName>DaUFDFBZ</def:datakindName>
      <def:column>Messwert</def:column>
      <def:validInterval>900</def:validInterval>
    </def:item>

    <def:item>
      <def:datakindName>DaUFDFBOberFlaeche</def:datakindName>
      <def:column>Messwert</def:column>
      <def:validInterval>900</def:validInterval>
    </def:item>

  </def:columnEntries>

  <def:active>false</def:active>
</def:mstDefinition>

=== verah-lab/c2vba/Source/Apps/datex2mst/mstBuilder/config/mstDefinition_TT_ASDA_MDM.xml
<?xml version="1.0" encoding="utf-8"?>
<def:mstDefinition
    xmlns:def="http://www.heuboe.de/mst/definition"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.heuboe.de/mst/definition mstDefinition.xsd ">
  <def:name>TT_ASDA_MDM</def:name>
  <def:description>ASDA/FOTO Reise-und Verlustzeiten auf RDS-Segmenten</def:description>
  <def:defVersion>1</def:defVersion>
  <def:columnEntries>
    <def:item>
      <def:datakindName>aca_losstime_ext</def:datakindName>
      <def:column>free_travel_time</def:column>
      <def:columnCharacteristic/>
      <def:validInterval>300</def:validInterval>
      <def:period>60</def:period>
    </def:item>
  </def:columnEntries>


  <def:active>false</def:active>
</def:mstDefinition>

=== verah-lab/c2vba/Source/Apps/datex2mst/mstBuilder/config/vzh/importMDM_D2DataMapping/data/mstDefinitionLVE_MDM.xml
<?xml version="1.0" encoding="utf-8"?>
<def:mstDefinition
    xmlns:def="http://www.heuboe.de/mst/definition"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.heuboe.de/mst/definition mstDefinition.xsd ">
  <def:name>LVE_MDM</def:name>
  <def:description>Messwertersetzte Verkehrsdaten fahrstreifenbezogen</def:description>
  <def:defVersion>1</def:defVersion>
  <def:qNameMode>qkurz</def:qNameMode>
  <def:columnEntries>
    <def:item>
      <def:datakindName>DaLVEKurzInterpolOpt0</def:datakindName>
      <def:column>qKFZ</def:column>
      <def:validInterval>1200</def:validInterval>
    </def:item>
    <def:item>
      <def:datakindName>DaLVEKurzInterpolOpt0</def:datakindName>
      <def:column>qLKW</def:column>
      <def:validInterval>1200</def:validInterval>
    </def:item>
    <def:item>
      <def:datakindName>DaLVEKurzInterpolOpt0</def:datakindName>
      <def:column>vPKW</def:column>
      <def:validInterval>1200</def:validInterval>
    </def:item>
    <def:item>
      <def:datakindName>DaLVEKurzInterpolOpt0</def:datakindName>
      <def:column>vLKW</def:column>
      <def:validInterval>1200</def:validInterval>
    </def:item>
  </def:columnEntries>
  
 	<def:filter>
		<def:objFilters>
		  <def:item exclusive="true">
			<def:referenceType>TLS</def:referenceType>
			<def:type>PMEASURE</def:type>
			<def:name>LVE MAINZ</def:name>
		  </def:item>
		</def:objFilters>
	</def:filter> 

  <def:active>false</def:active>
</def:mstDefinition>

=== verah-lab/c2vba/Source/Apps/datex2mst/mstBuilder/config/vzh/importMDM_D2DataMapping/data/mstDefinitionLVE_SimTD.xml
<?xml version="1.0" encoding="utf-8"?>
<def:mstDefinition
    xmlns:def="http://www.heuboe.de/mst/definition"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.heuboe.de/mst/definition mstDefinition.xsd ">
  <def:name>LVE</def:name>
  <def:description>Querschnitssbezogene Verkehrsdaten</def:description>
  <def:defVersion>1</def:defVersion>
  <def:columnEntries>

    <def:item>
      <def:datakindName>DaLVEAnalyseWerteOpt0</def:datakindName>
      <def:column>QLKW</def:column>
      <def:validInterval>1200</def:validInterval>
    </def:item>

    <def:item>
      <def:datakindName>DaLVEAnalyseWerteOpt0</def:datakindName>
      <def:column>VLKW</def:column>
      <def:validInterval>1200</def:validInterval>
    </def:item>

    <def:item>
      <def:datakindName>DaLVEAnalyseWerteOpt0</def:datakindName>
      <def:column>QPKW</def:column>
      <def:validInterval>1200</def:validInterval>
    </def:item>

    <def:item>
      <def:datakindName>DaLVEAnalyseWerteOpt0</def:datakindName>
      <def:column>VPKW</def:column>
      <def:validInterval>1200</def:validInterval>
    </def:item>

    <def:item>
      <def:datakindName>DaLVEAnalyseWerteOpt0</def:datakindName>
      <def:column>QKFZ</def:column>
      <def:validInterval>1200</def:validInterval>
    </def:item>

    <def:item>
      <def:datakindName>DaLVEAnalyseWerteOpt0</def:datakindName>
      <def:column>VKFZ</def:column>
      <def:validInterval>1200</def:validInterval>
    </def:item>

    <def:item>
      <def:datakindName>DaLVEAnalyseWerteOpt0</def:datakindName>
      <def:column>K</def:column>
      <def:validInterval>1200</def:validInterval>
    </def:item>

  </def:columnEntries>

  <def:active>false</def:active>
</def:mstDefinition>

=== verah-lab/c2vba/Source/Apps/datex2mst/mstBuilder/config/mstDefinition_LVE_MDM.xml
<?xml version="1.0" encoding="utf-8"?>
<def:mstDefinition
    xmlns:def="http://www.heuboe.de/mst/definition"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.heuboe.de/mst/definition mstDefinition.xsd ">
  <def:name>LVE_MDM_MMT2</def:name>
  <def:description>Messwertersetzte Verkehrsdaten fahrstreifenbezogen</def:description>
  <def:defVersion>1</def:defVersion>
  <def:qNameMode>qkurz</def:qNameMode>
  <def:columnEntries>
    <def:item>
      <def:datakindName>DaLVEKurzInterpolOpt0</def:datakindName>
      <def:column>qKFZ</def:column>
      <def:validInterval>1200</def:validInterval>
    </def:item>
    <def:item>
      <def:datakindName>DaLVEKurzInterpolOpt0</def:datakindName>
      <def:column>qLKW</def:column>
      <def:validInterval>1200</def:validInterval>
    </def:item>
    <def:item>
      <def:datakindName>DaLVEKurzInterpolOpt0</def:datakindName>
      <def:column>vPKW</def:column>
      <def:validInterval>1200</def:validInterval>
    </def:item>
    <def:item>
      <def:datakindName>DaLVEKurzInterpolOpt0</def:datakindName>
      <def:column>vLKW</def:column>
      <def:validInterval>1200</def:validInterval>
    </def:item>
  </def:columnEntries>

  <def:active>false</def:active>
</def:mstDefinition>
